"""Run every file in sql/ against PostgreSQL and check each result against pandas.

Usage (from the repo root, after scripts/load_to_postgres.py):
    python scripts/verify_sql.py

Writes reports/sql_check.md with each query's output and a PASS/FAIL line per check.
Exits with an error if any check fails.
"""
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sqlalchemy import create_engine

sys.path.insert(0, str(Path(__file__).resolve().parent))
from load_to_postgres import ROOT, load_clean  # noqa: E402

TOL = 1e-3   # SQL rounds to 4 decimals (in percent units), so compare to that precision


def run(engine, name):
    return pd.read_sql((ROOT / "sql" / name).read_text(), engine)


def close(a, b):
    return np.allclose(np.asarray(a, float), np.asarray(b, float), atol=TOL)


def main():
    url = os.environ.get("DATABASE_URL")
    if not url:
        sys.exit("Set DATABASE_URL first (see scripts/load_to_postgres.py)")
    engine = create_engine(url)
    df = load_clean()
    checks, sections = [], []

    # 01 group summary
    q = run(engine, "01_group_summary.sql").set_index("test_group")
    g = df.groupby("test_group").converted.agg(users="count", conversions="sum", rate="mean")
    checks.append(("01 users per group", (q.users == g.users).all()))
    checks.append(("01 conversions per group", (q.conversions == g.conversions).all()))
    checks.append(("01 conversion rate", close(q.conversion_rate_pct, 100 * g.rate)))
    sections.append(("01_group_summary.sql", q.reset_index()))

    # 02 lift by day
    q = run(engine, "02_lift_by_day.sql").set_index("most_ads_day")
    r = df.groupby(["most_ads_day", "test_group"]).converted.mean().unstack()
    checks.append(("02 lift by day", close(q.abs_lift_pp, 100 * (r.ad - r.psa).loc[q.index])))
    sections.append(("02_lift_by_day.sql", q.reset_index()))

    # 03 hour rank
    q = run(engine, "03_hour_rank.sql")
    h = df.groupby(["test_group", "most_ads_hour"]).converted.mean()
    checks.append(("03 hourly conversion rate",
                   close(q.conv_rate_pct, 100 * h.loc[list(zip(q.test_group, q.most_ads_hour))].values)))
    sections.append(("03_hour_rank.sql (top 5 per group)", q.groupby("test_group").head(5)))

    # 04 z-test in SQL vs statsmodels
    from statsmodels.stats.proportion import proportions_ztest, confint_proportions_2indep
    q = run(engine, "04_ztest.sql").iloc[0]
    x = df.groupby("test_group").converted.sum(); n = df.groupby("test_group").size()
    z, _ = proportions_ztest([x["ad"], x["psa"]], [n["ad"], n["psa"]], alternative="larger")
    lo, hi = confint_proportions_2indep(x["ad"], n["ad"], x["psa"], n["psa"], compare="diff", method="wald")
    checks.append(("04 z statistic", abs(float(q.z_stat) - z) < TOL))
    checks.append(("04 95% CI", close([q.ci95_low_pp, q.ci95_high_pp], [100 * lo, 100 * hi])))
    sections.append(("04_ztest.sql", q.to_frame().T))

    # 05 exposure buckets
    q = run(engine, "05_exposure_buckets.sql").set_index("ads_bucket")
    b = pd.cut(df.total_ads, [0, 5, 20, 50, np.inf], labels=["1-5", "6-20", "21-50", "51+"])
    e = df.assign(b=b).groupby(["b", "test_group"], observed=True).converted.mean().unstack()
    checks.append(("05 lift by exposure bucket", close(q.abs_lift_pp, 100 * (e.ad - e.psa).loc[q.index])))
    sections.append(("05_exposure_buckets.sql", q.reset_index()))

    lines = ["# SQL vs pandas verification", "",
             "Generated by `scripts/verify_sql.py` against PostgreSQL. Every SQL result is recomputed in pandas.", "",
             "| Check | Result |", "|---|---|"]
    lines += [f"| {name} | {'PASS' if ok else 'FAIL'} |" for name, ok in checks]
    for title, frame in sections:
        lines += ["", f"## {title}", "", frame.to_markdown(index=False)]
    (ROOT / "reports" / "sql_check.md").write_text("\n".join(lines) + "\n")

    for name, ok in checks:
        print(f"{'PASS' if ok else 'FAIL'}  {name}")
    if not all(ok for _, ok in checks):
        sys.exit("Some SQL checks failed")
    print("All SQL results match pandas. Report: reports/sql_check.md")


if __name__ == "__main__":
    main()
